# Travis CI Configuration File

os: linux
dist: xenial

language: php

services:
  - mysql

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6

env:
  - WP_VERSION=master
  - WP_VERSION=5.5
  - WP_VERSION=5.4
  - WP_VERSION=5.3

jobs:
  fast_finish: true

before_install:
  - |
    # Remove Xdebug for a huge performance increase:
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    fi

# Clone WordPress and configure the testing environment.
before_script:
  - mysql --version
  - phpenv versions
  - php --version
  - php -m
  - |
    # Install the specified version of PHPUnit depending on the PHP version:
    if [[ 1 == 1 ]]; then
      case "$TRAVIS_PHP_VERSION" in
        7.4|7.3|7.2|7.1)
          echo "Using PHPUnit 7.x for PHP version $TRAVIS_PHP_VERSION"
          composer require "phpunit/phpunit:^7"
          ;;
        7.0)
          echo "Using PHPUnit 6.x for PHP version $TRAVIS_PHP_VERSION"
          composer require "phpunit/phpunit:^6"
          ;;
        5.6)
          echo "Using PHPUnit 5.x for PHP version $TRAVIS_PHP_VERSION"
          composer require "phpunit/phpunit:^5"
          ;;
        *)
          echo "No PHPUnit version handling for PHP version $TRAVIS_PHP_VERSION"
          exit 1
          ;;
      esac
    fi
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - git --version
  - locale -a
  - export WP_DEVELOP_DIR=/tmp/wordpress
  - export WP_TESTS_DIR=$WP_DEVELOP_DIR/tests/phpunit/
  - export PLUGIN_SLUG=$(basename $(pwd))
  - export PLUGIN_SLUG_LC=${PLUGIN_SLUG,,}
  - git clone --depth=50 --branch="$WP_VERSION" git://develop.git.wordpress.org/ $WP_DEVELOP_DIR
  - cd ..
  - mv "$PLUGIN_SLUG" "$WP_DEVELOP_DIR/src/wp-content/plugins/$PLUGIN_SLUG_LC"
  - cd $WP_DEVELOP_DIR
  - mysql -e "CREATE DATABASE wordpress_tests;" -uroot
  - cp wp-tests-config-sample.php wp-tests-config.php
  - sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
  - sed -i "s/yourusernamehere/travis/" wp-tests-config.php
  - sed -i "s/yourpasswordhere//" wp-tests-config.php
  - cd "$WP_DEVELOP_DIR/src/wp-content/plugins/$PLUGIN_SLUG_LC"

script:
  - bash tests/run-tests.sh
