# Travis CI Configuration File

sudo: false

language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

env:
  - WP_VERSION=master WP_MULTISITE=0
  - WP_VERSION=master WP_MULTISITE=1
  - WP_VERSION=4.7.0 WP_MULTISITE=0
  - WP_VERSION=4.7.0 WP_MULTISITE=1
  - WP_VERSION=4.6.1 WP_MULTISITE=0
  - WP_VERSION=4.6.1 WP_MULTISITE=1
  - WP_VERSION=4.5.4 WP_MULTISITE=0
  - WP_VERSION=4.5.4 WP_MULTISITE=1
  - WP_VERSION=4.4.5 WP_MULTISITE=0
  - WP_VERSION=4.4.5 WP_MULTISITE=1
  - WP_VERSION=4.3.6 WP_MULTISITE=0
  - WP_VERSION=4.3.6 WP_MULTISITE=1

# Clone WordPress and configure the testing environment.
before_script:
  - export WP_DEVELOP_DIR=/tmp/wordpress
  - export WP_TESTS_DIR=$WP_DEVELOP_DIR/tests/phpunit/
  - export PLUGIN_SLUG=$(basename $(pwd))
  - export PLUGIN_SLUG_LC=${PLUGIN_SLUG,,}
  - git clone --depth=50 --branch="$WP_VERSION" git://develop.git.wordpress.org/ $WP_DEVELOP_DIR
  - cd ..
  - mv "$PLUGIN_SLUG" "$WP_DEVELOP_DIR/src/wp-content/plugins/$PLUGIN_SLUG_LC"
  - cd $WP_DEVELOP_DIR
  - mysql -e "CREATE DATABASE wordpress_tests;" -uroot
  - cp wp-tests-config-sample.php wp-tests-config.php
  - sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
  - sed -i "s/yourusernamehere/travis/" wp-tests-config.php
  - sed -i "s/yourpasswordhere//" wp-tests-config.php
  - cd "$WP_DEVELOP_DIR/src/wp-content/plugins/$PLUGIN_SLUG_LC"

script: phpunit
