name: Static Analysis

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

on:
  push:
    branches:
      - main
    paths:
      # Any change to a PHP file should run checks.
      - '**.php'
      # These files configure Composer. Changes could affect the outcome.
      - 'composer.*'
      # This file configures PHPStan. Changes could affect the outcome.
      - 'phpstan.xml.dist'
      # Changes to workflow files should always verify all workflows are successful.
      - '.github/workflows/*.yml'
  pull_request:
    branches:
      - main
    paths:
      # Any change to a PHP file should run checks.
      - '**.php'
      # These files configure Composer. Changes could affect the outcome.
      - 'composer.*'
      # This file configures PHPStan. Changes could affect the outcome.
      - 'phpstan.xml.dist'
      # Changes to workflow files should always verify all workflows are successful.
      - '.github/workflows/*.yml'
  schedule:
    - cron: '45 3 * * SUN'
  workflow_dispatch:

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  # Runs PHP static analysis checks.
  #
  # Violations are reported inline with annotations.
  #
  # Performs the following steps:
  # - Sets up PHP.
  # - Checks out the repository.
  # - Installs Composer dependencies.
  # - Makes Composer packages available globally.
  # - Runs PHPStan.

  phpstan:
    name: PHP static analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # v2.36.0
        with:
          php-version: 'latest'
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout TablePress repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install Composer dependencies
        uses: ramsey/composer-install@3cf229dc2919194e9e36783941438d17239e8520 # v3.1.1

      - name: Make Composer packages available globally
        run: echo "${PWD}/vendor/bin" >> $GITHUB_PATH

      - name: Run PHP static analysis checks
        id: phpstan
        run: phpstan analyze --memory-limit 2G --error-format=github

  failed-workflow:
    name: Failed workflow tasks
    runs-on: ubuntu-latest
    permissions:
      actions: write
    needs: [ phpstan ]
    if: |
      always() &&
      github.event_name != 'pull_request' &&
      github.run_attempt < 2 &&
      (
        needs.phpstan.result == 'cancelled' || needs.phpstan.result == 'failure'
      )
    steps:
      - name: Dispatch workflow run
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'failed-workflow.yml',
              ref: 'main',
              inputs: {
                run_id: '${{ github.run_id }}'
              }
            });
